export const listaRiscosEspeciais = [
  'Tanques de combustível (substância e capacidade).',
  'Casa de caldeira ou vasos de pressão.',
  'Dutos e aberturas que possibilitem a propagação do calor, exceto aqueles próprios de medidas de segurança.',
  'Cabinas de pintura.',
  'Áreas com risco de explosão.',
  'Centrais prediais de gases inflamáveis.',
  'Depósitos de metais pirofóricos.',
  'Comercialização, armazenamento, manipulação e/ou utilização de Gás Liquefeito de Petróleo (GLP), Gás Natural (GN) e/ou demais gases combustíveis ou inflamáveis.',
  'Manipulação e/ou armazenamento de produtos perigosos, explosivos e líquidos inflamáveis ou combustíveis.',
  'Cobertura de sapê, piaçava ou similares.',
  'Heliporto ou heliponto.',
  'Comércio de fogos de artifício e pirotecnia.',
  'Pátio de contêineres.',
  'Cozinhas profissionais.',
  'Subestações.',
  'Casa de bombas.',
  'Edificação que compõe o patrimônio cultural.',
  'Gerador.',
  'Casa de força elétrica.',
  'Casa de máquinas.',
  'Galeria de transmissão.',
  'Incinerador.',
  'Transformador.',
  'Ponte rolante.',
  'Quadro de redução para baixa tensão.',
  'Contêiner de telefonia.',
  'Painéis fotovoltaicos, quando instalados sobre edificação.',
  'Outros riscos que necessitem de medidas de segurança contra incêndio e pânico específicas.',
];
