const tabelac1 = [
  'Acetileno',
  'Acetileno dissolvido',
  'Acetona',
  'Acrílico',
  'Açúcar',
  'Amido',
  'Algodão',
  'Álcool Alílico',
  'Álcool Amílico',
  'Álcool Etílico',
  'Álcool metílico',
  'Benzeno',
  'Benzina',
  'Celulose',
  'Biodiesel',
  'Borracha espuma',
  'Borracha em tiras',
  'Butano',
  'Cacau em pó',
  'Café',
  'Cafeína',
  'Cálcio',
  'Carbono',
  'Carvão',
  'Celulose',
  'Dietilcetona',
  'Dietileter',
  'Epóxi',
  'Etano',
  'Etanol',
  'Eteno',
  'Éter amílico',
  'Éter etílico',
  'Etileno',
  'Etino',
  'Enxofre',
  'Farinha de trigo',
  'Hexaptano',
  'Fenol',
  'Fibra sintética 6,6',
  'Fósforo',
  'Gás Natural',
  'Gasolina',
  'Glicerina',
  'Gordura e óleo vegetal',
  'Grãos',
  'Graxa, lubrificante',
  'Heptano',
  'Hexametileno',
  'Hexano',
  'Metanol',
  'Monóxido de carbono',
  'Nafta',
  'N-Butano',
  'Nitrocelulose',
  'N-Octano',
  'N-Pentano',
  'Óleo de linhaça',
  'Óleo vegetal',
  'Palha',
  'Papel',
  'Parafina',
  'Petróleo',
  'Plástico',
  'Poliacrilonitrico',
  'Policarbonato',
  'Poliéster',
  'Poliestireno',
  'Polietileno',
  'Polimetilmetacrilico',
  'Polioximetileno',
  'Poliuretano',
  'Polivinilclorido',
  'Polipropileno',
  'Propano',
  'Cereais',
  'C-Heptano',
  'C-Pentano',
  'C-Propano',
  'C-Hexano',
  'Chocolate',
  'Cloreto de polivinil',
  'Couro',
  'Creosoto/fenol',
  'D-glucose',
  'Diesel',
  'Dietilamina',
  'Hidreto de sódio',
  'Hidrogênio',
  'Hidreto de magnésio',
  'Látex',
  'Lã',
  'Leite em pó',
  'Linho',
  'Linóleo',
  'Lixo de cozinha',
  'Madeira',
  'Magnésio',
  'Manteiga',
  'Metano',
  'PVC',
  'Resina de fenol',
  'Resina de uréia',
  'Resina melamínica',
  'Seda',
  'Sisal',
  'Sódio',
  'Sulfureto de carbono',
  'Tabaco',
  'Tolueno',
  'Turfa',
  'Ureia (ver também resina de ureia)',
  'Viscose',
];

const valorestabelac1 = [
  50, 17, 30, 28, 17, 17, 18, 34, 42, 25, 21, 40, 42, 16, 39, 37, 32, 46, 17,
  17, 21, 4, 34, 36, 16, 34, 37, 34, 47, 26, 50, 42, 34, 50, 48, 8.4, 17, 46,
  34, 29, 25, 26, 47, 17, 42, 17, 41, 46, 46, 46, 19, 10, 42, 45, 8, 44, 45, 37,
  42, 16, 17, 46, 41, 31, 30, 29, 31, 39, 44, 24, 15, 23, 16, 43, 46, 17, 46,
  46, 50, 46, 25, 17, 21, 19, 37, 15, 43, 42, 9, 143, 17, 44, 23, 17, 17, 2, 18,
  19, 25, 37, 50, 17, 25, 21, 18, 19, 17, 4.5, 12.5, 17, 42, 34, 9, 17,
];

const DeterministicoTabela = () => {
  const material = tabelac1;
  const valores = valorestabelac1;
  return { material, valores };
};

export default DeterministicoTabela;
