export const CNAE = [
  '1621-8/00 - Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada',
  '19xx-x/xx - Fabricação de coque, de produtos derivados do petróleo e de biocombustíveis',
  '3520-4/0x - Eletricidade, gás e outras utilidades',
  '35xx-x/xx - Eletricidade, gás e outras utilidades',
  '4679-6/01 - Comércio atacadista de tintas, vernizes e similares',
  '4681-8/xx - Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP',
  '4682-6/xx - Comércio atacadista de gás liquefeito de petróleo (GLP)',
  '4684-2/xx - Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos',
  '4686-9/xx - Comércio atacadista de papel e papelão em bruto e de embalagens',
  '4687-7/01 - Comércio atacadista de resíduos de papel e papelão',
  '4687-7/02 - Comércio atacadista de resíduos e sucatas não-metálicos, exceto de papel e papelão',
  '4731-8/00 - Comércio varejista de combustíveis para veículos automotores',
  '4784-9/00 - Comércio varejista de gás liquefeito de petróleo (GLP)',
  '4789-0/06 - Comércio varejista de fogos de artifício e artigos pirotécnicos',
  '8511-2/00 - Educação infantil – creche',
  '8512-1/00 - Educação infantil - pré-escola',
  '861x-x/xx - Atividades de atendimento hospitalar',
]